/**
 * T3.5 — invites, ownership transfer and disable.
 *
 * NOTE ON THE SCHEMA: `user_invites` is created by `ensureUserInvitesTable()`
 * (tests/helpers/user-invites.ts) with a raw `CREATE TABLE IF NOT EXISTS` that
 * matches `src/db/schema/index.ts` exactly.
 * The migration for this wave is generated by the orchestrator once every
 * concurrent schema edit has landed, so `drizzle/migrations` does not have the
 * table yet. Delete `ensureUserInvitesTable()` when the migration exists.
 */
import { and, eq } from "drizzle-orm";
import { beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import {
	auditLogs,
	conversations,
	domains,
	folders,
	mailboxes,
	organizations,
	sessions,
	userInvites,
	users,
} from "@/db/schema";
import { createInvite } from "@/lib/accounts/invites";
import { hashPassword } from "@/lib/auth/password";
import { SESSION_COOKIE, createSession, getUserFromSession } from "@/lib/auth/session";
import { createDb, hasTestDatabase } from "./helpers/db";
import { ensureUserInvitesTable } from "./helpers/user-invites";

/** Cookie jar backing the mocked `next/headers`. */
const cookieJar = new Map<string, string>();

vi.mock("next/headers", () => ({
	cookies: async () => ({
		get: (name: string) => {
			const value = cookieJar.get(name);
			return value === undefined ? undefined : { name, value };
		},
	}),
}));

const ORG_A = "org_inv_a";
const ORG_B = "org_inv_b";

const ADMIN_A = "usr_inv_admin_a";
const MEMBER_A = "usr_inv_member_a";
const HEIR_A = "usr_inv_heir_a";
const ADMIN_B = "usr_inv_admin_b";

const DOMAIN_A = "dom_inv_a";
const MAILBOX_ADMIN_A = "mbx_inv_admin_a";
const MAILBOX_MEMBER_A = "mbx_inv_member_a";
const CONVERSATION_A = "cnv_inv_a";
const FOLDER_A = "fld_inv_a";

async function seed(): Promise<void> {
	const db = createDb();

	await db.insert(organizations).values([
		{ id: ORG_A, name: "Org A", slug: "inv-org-a", status: "active" },
		{ id: ORG_B, name: "Org B", slug: "inv-org-b", status: "active" },
	]);

	await db.insert(users).values([
		{
			id: ADMIN_A,
			organizationId: ORG_A,
			email: "admin@inv-a.test",
			passwordHash: hashPassword("admin-password"),
			name: "Admin A",
			role: "admin",
		},
		{
			id: MEMBER_A,
			organizationId: ORG_A,
			email: "member@inv-a.test",
			passwordHash: hashPassword("member-password"),
			name: "Member A",
			role: "user",
			createdByUserId: ADMIN_A,
		},
		{
			id: HEIR_A,
			organizationId: ORG_A,
			email: "heir@inv-a.test",
			passwordHash: hashPassword("heir-password"),
			name: "Heir A",
			role: "user",
			createdByUserId: ADMIN_A,
		},
		{
			id: ADMIN_B,
			organizationId: ORG_B,
			email: "admin@inv-b.test",
			passwordHash: hashPassword("other-password"),
			name: "Admin B",
			role: "admin",
		},
	]);

	await db.insert(domains).values({
		id: DOMAIN_A,
		organizationId: ORG_A,
		userId: ADMIN_A,
		hostname: "inv-a.test",
		zoneId: "zone_inv_a",
	});

	await db.insert(mailboxes).values([
		{
			id: MAILBOX_ADMIN_A,
			organizationId: ORG_A,
			userId: ADMIN_A,
			domainId: DOMAIN_A,
			localPart: "admin",
			type: "personal",
		},
		{
			id: MAILBOX_MEMBER_A,
			organizationId: ORG_A,
			userId: MEMBER_A,
			domainId: DOMAIN_A,
			localPart: "member",
			type: "personal",
		},
	]);

	await db.insert(conversations).values({
		id: CONVERSATION_A,
		organizationId: ORG_A,
		mailboxId: MAILBOX_MEMBER_A,
		subject: "Hello",
		assignedUserId: MEMBER_A,
	});

	await db.insert(folders).values({
		id: FOLDER_A,
		organizationId: ORG_A,
		userId: MEMBER_A,
		mailboxId: MAILBOX_MEMBER_A,
		name: "Receipts",
	});
}

async function signIn(userId: string): Promise<string> {
	const token = await createSession({ DB: createDb() } as unknown as CloudflareEnv, userId);
	cookieJar.clear();
	cookieJar.set(SESSION_COOKIE, token);
	return token;
}

function get(url: string): Request {
	return new Request(`http://localhost${url}`);
}

function send(url: string, method: string, body?: unknown): Request {
	return new Request(`http://localhost${url}`, {
		method,
		headers: { "Content-Type": "application/json" },
		...(body === undefined ? {} : { body: JSON.stringify(body) }),
	});
}

function routeCtx<P extends Record<string, string>>(params: P) {
	return { params: Promise.resolve(params) };
}

describe.skipIf(!hasTestDatabase())("accounts: invites, transfer, disable (T3.5)", () => {
	beforeAll(async () => {
		// The route handlers build their env from process.env.
		process.env.DATABASE_URL = process.env.TEST_DATABASE_URL;
		// `getEnv()` refuses a half-configured mail transport; nothing here sends.
		if (!!process.env.EDGE_WORKER_URL !== !!process.env.EDGE_WORKER_SECRET) {
			delete process.env.EDGE_WORKER_URL;
			delete process.env.EDGE_WORKER_SECRET;
		}
		await ensureUserInvitesTable();
	});

	beforeEach(async () => {
		cookieJar.clear();
		await seed();
	});

	it("invite -> set password -> login, and every old session is gone", async () => {
		const db = createDb();
		const oldSession = await signIn(MEMBER_A);
		const invite = await createInvite(db, {
			organizationId: ORG_A,
			userId: MEMBER_A,
			createdByUserId: ADMIN_A,
		});

		// The public validity check needs no session at all.
		cookieJar.clear();
		const check = await import("@/app/api/invites/[token]/route");
		const valid = await check.GET(
			get(`/api/invites/${invite.token}`),
			routeCtx({ token: invite.token }),
		);
		expect(valid.status).toBe(200);
		expect(((await valid.json()) as { invite: { email: string } }).invite.email).toBe(
			"member@inv-a.test",
		);

		const accept = await import("@/app/api/invites/[token]/accept/route");
		const accepted = await accept.POST(
			send(`/api/invites/${invite.token}/accept`, "POST", { password: "brand-new-password" }),
			routeCtx({ token: invite.token }),
		);
		expect(accepted.status).toBe(200);

		// Sessions held before the invite was accepted no longer resolve.
		const remaining = await db.select().from(sessions).where(eq(sessions.userId, MEMBER_A));
		expect(remaining).toHaveLength(0);
		const env = { DB: db } as unknown as CloudflareEnv;
		expect(await getUserFromSession(env, oldSession)).toBeNull();

		const login = await import("@/app/api/auth/login/route");
		const loggedIn = await login.POST(
			send("/api/auth/login", "POST", {
				email: "member@inv-a.test",
				password: "brand-new-password",
			}),
		);
		expect(loggedIn.status).toBe(200);

		// The old password is dead.
		const stale = await login.POST(
			send("/api/auth/login", "POST", {
				email: "member@inv-a.test",
				password: "member-password",
			}),
		);
		expect(stale.status).toBe(401);
	});

	it("rejects an expired token and a token that was already used", async () => {
		const db = createDb();
		const accept = await import("@/app/api/invites/[token]/accept/route");
		const check = await import("@/app/api/invites/[token]/route");

		const expired = await createInvite(db, { organizationId: ORG_A, userId: MEMBER_A });
		await db
			.update(userInvites)
			.set({ expiresAt: new Date(Date.now() - 60_000) })
			.where(eq(userInvites.id, expired.id));

		expect(
			(
				await check.GET(get(`/api/invites/${expired.token}`), routeCtx({ token: expired.token }))
			).status,
		).toBe(404);
		expect(
			(
				await accept.POST(
					send(`/api/invites/${expired.token}/accept`, "POST", { password: "irrelevant-1" }),
					routeCtx({ token: expired.token }),
				)
			).status,
		).toBe(404);

		const once = await createInvite(db, { organizationId: ORG_A, userId: MEMBER_A });
		expect(
			(
				await accept.POST(
					send(`/api/invites/${once.token}/accept`, "POST", { password: "first-password" }),
					routeCtx({ token: once.token }),
				)
			).status,
		).toBe(200);
		// Second use of the same link.
		expect(
			(
				await accept.POST(
					send(`/api/invites/${once.token}/accept`, "POST", { password: "second-password" }),
					routeCtx({ token: once.token }),
				)
			).status,
		).toBe(404);

		// The first password is the one that stuck.
		const login = await import("@/app/api/auth/login/route");
		expect(
			(
				await login.POST(
					send("/api/auth/login", "POST", {
						email: "member@inv-a.test",
						password: "second-password",
					}),
				)
			).status,
		).toBe(401);
		expect(
			(
				await login.POST(
					send("/api/auth/login", "POST", {
						email: "member@inv-a.test",
						password: "first-password",
					}),
				)
			).status,
		).toBe(200);
	});

	it("a resend invalidates the previous invite link", async () => {
		const db = createDb();
		const first = await createInvite(db, { organizationId: ORG_A, userId: MEMBER_A });
		const second = await createInvite(db, { organizationId: ORG_A, userId: MEMBER_A });

		const check = await import("@/app/api/invites/[token]/route");
		expect(
			(await check.GET(get(`/api/invites/${first.token}`), routeCtx({ token: first.token })))
				.status,
		).toBe(404);
		expect(
			(await check.GET(get(`/api/invites/${second.token}`), routeCtx({ token: second.token })))
				.status,
		).toBe(200);
		expect(await db.select().from(userInvites).where(eq(userInvites.userId, MEMBER_A))).toHaveLength(
			1,
		);
	});

	it("transfer moves mailboxes and conversations, and refuses a target of another org", async () => {
		const db = createDb();
		const transfer = await import("@/app/api/accounts/[id]/transfer/route");

		await signIn(ADMIN_A);
		const crossOrg = await transfer.POST(
			send(`/api/accounts/${MEMBER_A}/transfer`, "POST", { toUserId: ADMIN_B }),
			routeCtx({ id: MEMBER_A }),
		);
		expect(crossOrg.status).toBe(404);

		// Nothing moved.
		const [untouched] = await db.select().from(mailboxes).where(eq(mailboxes.id, MAILBOX_MEMBER_A));
		expect(untouched?.userId).toBe(MEMBER_A);

		const moved = await transfer.POST(
			send(`/api/accounts/${MEMBER_A}/transfer`, "POST", { toUserId: HEIR_A }),
			routeCtx({ id: MEMBER_A }),
		);
		expect(moved.status).toBe(200);

		const [mailbox] = await db.select().from(mailboxes).where(eq(mailboxes.id, MAILBOX_MEMBER_A));
		expect(mailbox?.userId).toBe(HEIR_A);
		const [conversation] = await db
			.select()
			.from(conversations)
			.where(eq(conversations.id, CONVERSATION_A));
		expect(conversation?.assignedUserId).toBe(HEIR_A);
		const [folder] = await db.select().from(folders).where(eq(folders.id, FOLDER_A));
		expect(folder?.userId).toBe(HEIR_A);

		const [audit] = await db
			.select()
			.from(auditLogs)
			.where(and(eq(auditLogs.organizationId, ORG_A), eq(auditLogs.action, "account.transfer")));
		expect(audit?.targetUserId).toBe(MEMBER_A);
		expect(JSON.parse(audit?.metadata ?? "{}")).toMatchObject({ toUserId: HEIR_A });
	});

	it("a disabled account loses its sessions and cannot log in", async () => {
		const db = createDb();
		await signIn(MEMBER_A);
		expect(await db.select().from(sessions).where(eq(sessions.userId, MEMBER_A))).toHaveLength(1);

		await signIn(ADMIN_A);
		const account = await import("@/app/api/accounts/[id]/route");
		const patched = await account.PATCH(
			send(`/api/accounts/${MEMBER_A}`, "PATCH", {
				name: "Member A",
				role: "user",
				disabled: true,
				canManageMailboxes: false,
			}),
			routeCtx({ id: MEMBER_A }),
		);
		expect(patched.status).toBe(200);
		expect(await db.select().from(sessions).where(eq(sessions.userId, MEMBER_A))).toHaveLength(0);

		const login = await import("@/app/api/auth/login/route");
		const refused = await login.POST(
			send("/api/auth/login", "POST", {
				email: "member@inv-a.test",
				password: "member-password",
			}),
		);
		expect(refused.status).toBe(403);
	});
});
