import { sql } from "drizzle-orm";
import { createDb, migrateTestDatabase } from "./db";

/**
 * Adds the T6.1 `api_keys` columns to the test database.
 *
 * The combined migration for this wave is generated by the orchestrator after
 * all the concurrent schema edits land, so `drizzle/migrations` does not have
 * these columns yet. Every test file that touches `api_keys` calls this in its
 * `beforeAll`; it is idempotent, and DDL survives `truncateAll()`.
 *
 * Delete this helper once the migration exists.
 */
export async function ensureApiKeyColumns(): Promise<void> {
	await migrateTestDatabase();
	const db = createDb();
	await db.execute(sql`
		ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS hash_algo text NOT NULL DEFAULT 'bcrypt';
	`);
	await db.execute(sql`ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS expires_at timestamptz;`);
	await db.execute(sql`ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS revoked_at timestamptz;`);
	await db.execute(sql`ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS last_used_ip text;`);
}
