import { sql } from "drizzle-orm";
import { DEFAULT_ORGANIZATION_ID } from "@/lib/organizations/constants";
import { createDb, migrateTestDatabase } from "./db";

/**
 * Creates the T3.5 `user_invites` table, matching `src/db/schema/index.ts`
 * exactly.
 *
 * The combined migration for this wave is generated by the orchestrator after
 * every concurrent schema edit has landed, so `drizzle/migrations` does not have
 * this table yet. Each test file that touches invites calls this in its
 * `beforeAll`; it is idempotent, and DDL survives `truncateAll()`.
 *
 * Delete this helper once the migration exists.
 */
export async function ensureUserInvitesTable(): Promise<void> {
	await migrateTestDatabase();
	const db = createDb();
	// `sql.raw`: Postgres takes no bind parameters in a DDL `DEFAULT`.
	await db.execute(
		sql.raw(`
		CREATE TABLE IF NOT EXISTS "user_invites" (
			"id" text PRIMARY KEY NOT NULL,
			"organization_id" text NOT NULL DEFAULT '${DEFAULT_ORGANIZATION_ID}'
				REFERENCES "organizations"("id") ON DELETE cascade,
			"user_id" text NOT NULL REFERENCES "users"("id") ON DELETE cascade,
			"token_hash" text NOT NULL UNIQUE,
			"expires_at" timestamptz NOT NULL,
			"accepted_at" timestamptz,
			"created_by_user_id" text REFERENCES "users"("id") ON DELETE set null,
			"created_at" timestamptz NOT NULL DEFAULT now()
		)
	`),
	);
	await db.execute(
		sql`CREATE INDEX IF NOT EXISTS "user_invites_user_idx" ON "user_invites" ("user_id")`,
	);
	await db.execute(
		sql`CREATE INDEX IF NOT EXISTS "user_invites_organization_idx" ON "user_invites" ("organization_id")`,
	);
}
